# Site settings
title: Mateusz Zaremba - Portfolio
description: "Mateusz Zaremba"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "http://matzar.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: Mateusz Zaremba
user_title: matzar
email: matzaremba@icloud.com
twitter_username: jollyjellycoco
github_username:  matzar
#gplus_username:  loremipsum
linkedin_public_url: mateusz-zaremba # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
#disqus_username: loremipsum
#profile_picture: '/png/me.png'
profile_picture: /assets/img/me.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: posts
      url: /posts
      key_trigger: 2
    - title: projects
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: source
      url: /about
      key_trigger: 5
  section_2:
    - title: cv
      url: /cv
      key_trigger: c
    - title: github
      url: http://www.github.com/matzar
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/jollyjellycoco
      new_tab: true
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: PSVita Game
    url: /psvita
  - name: SFML Networking
    url: /sfml_networking
  - name: C++ AMP Mandelbrot set
    url: /amp_mandelbrot
  - name: OpenGL 1.1
    url: /opengl
  - name: DirectX 11 HLSL
    url: /directx
  - name: Game Boy Advance BATTLE CITY remake
    url: /battle_city
  - name: simple darts simulator
    url: /darts_simulator

# team projects
team:
  - name: Global Game Jam 2016
    url: /ggj2016
  - name: Serious Game Jam 2018
    url: /chemistry_game_jam

#projects:
#  - name: Timex (Windows | Unity)
#    url: https://github.com/RetrospectAbertay/Lit
#  - name: Space Whales (Windows | UE4)
#    url: https://github.com/GeorgeRankin/space-whales
#  - name: Rhythm Game (Windows | Unity)
#    url: https://github.com/jctwood/EGD-RhythmGame

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
