# Site settings
title: Mateusz Zaremba - Portfolio
description: "Mateusz Zaremba"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "http://matzar.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: Mateusz Zaremba
user_title: matzar
email: mat.zar@icloud.com
skype: gb6ynq6t8EeD
discord: discord
github_username: matzar
# discord_invite: cj5rgDN # Example: Discord server invite gg extension like in 'https://discord.gg/cj5rgDN'
twitter_username: jollyjellycoco
linkedin_public_url: mateusz-zaremba # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
#disqus_username: carrotcake
profile_picture: /assets/img/me.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: posts
      url: /posts
      key_trigger: 2
    - title: projects
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: source
      url: /about
      key_trigger: 5
  section_2:
    - title: cv
      url: https://matzar.github.io/markdown-cv/
      key_trigger: c
    - title: hear
      url: /hear
      key_trigger: h
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: PSVita Game
    url: /psvita
  - name: SFML Networking
    url: /sfml_networking
  - name: C++ AMP Mandelbrot set
    url: /amp_mandelbrot
  - name: OpenGL 1.1
    url: /opengl
  - name: DirectX 11 HLSL
    url: /directx
  - name: Game Boy Advance BATTLE CITY remake
    url: /battle_city
  - name: Simple darts simulator
    url: /darts_simulator
  - name: My first Unity game
    url: /dragon_maze

# team projects
team:
  - name: Global Game Jam 2016
    url: /ggj2016
  - name: Serious Game Jam 2018
    url: /chemistry_game_jam
  - name: 4-hour game jam
    url: /visual_novel
  - name: Space Whales
    url: /space_whales
  - name: Rainbow Dash infinite runner
    url: /rainbow_dash

git:
  - name: ModernCpp
    url: https://github.com/matzar/ModernCpp
  - name: Face emotion recogntion
    url: https://github.com/matzar/face_emotion_recognition
  - name: PSVita Game
    url: https://github.com/matzar/PSVita-Game
  - name: SFML Networking
    url: https://github.com/matzar/SFML-Networking
  - name: C++ AMP Mandelbrot set
    url: https://github.com/matzar/Mandelbrot-AMP
  - name: OpenGL 1.1
    url: https://github.com/matzar/OpenGL
  - name: DirectX 11 HLSL
    url: https://github.com/matzar/DirectX-Shaders
  - name: Game Boy Advance BATTLE CITY remake
    url: https://github.com/matzar/BattleCity-GBA
  - name: Simple darts simulator
    url: https://github.com/matzar/darts-game
  - name: My first Unity game
    url: https://github.com/matzar/DragonMazeTheGame
  - name: Serious Game Jam 2018
    url: https://github.com/matzar/SeriousGameJam
  - name: 4-hour game jam
    url: https://github.com/matzar/ren-py
  - name: Space Whales
    url: https://github.com/GeorgeRankin/space-whales
  - name: Rainbow Dash infinite runner
    url: https://github.com/matzar/infinite-runner
  - name: Timex
    url: https://github.com/RetrospectAbertay/Lit
  - name: Line Tracer UE4
    url: https://github.com/matzar/LineTracer


#projects:
#  - name: Timex (Windows | Unity)
#    url: https://github.com/RetrospectAbertay/Lit
#  - name: Space Whales (Windows | UE4)
#    url: https://github.com/GeorgeRankin/space-whales
#  - name: Rhythm Game (Windows | Unity)
#    url: https://github.com/jctwood/EGD-RhythmGame

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
